# Generated by Django 5.0 on 2024-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_component_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronic Component', 'Electronic Component'), ('Sensors', 'Sensors'), ('Development Board', 'Development Board'), ('Motors', 'Motors')], max_length=20, null=True),
        ),
    ]
