# Generated by Django 5.0 on 2024-01-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_component_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronic Component', 'Electronic Component'), ('Sensors', 'Sensors'), ('Development Boards', 'Development Boards'), ('Motors', 'Motors')], max_length=20, null=True),
        ),
    ]
