# Generated by Django 5.0 on 2024-02-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_approval'),
        ('home', '0009_alter_component_category'),
    ]

    operations = [
    ]
