# Generated by Django 4.2.7 on 2024-02-03 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_order_approval"),
        ("home", "0009_alter_component_category"),
    ]

    operations = []
