# Generated by Django 5.0 on 2024-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20240203_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
