# Generated by Django 4.2.7 on 2024-02-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_merge_20240203_1411"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("number", models.IntegerField()),
                ("message", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="component",
            name="category",
        ),
        migrations.RemoveField(
            model_name="order",
            name="approval",
        ),
    ]
